obstacle_range: 4.0
raytrace_range: 4.0
footprint: [[0, 0], [-0.2, 0], [-0.2, 0.19], [0.2 , 0.19], [0.2, -0.19], [-0.2, -0.19], [-0.2, 0]]
inflation_radius: 0.10

max_obstacle_height: 0.6
min_obstacle_height: 0.08

#observation_sources: laser_scan_sensor point_cloud_sensor
observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: /laser, data_type: LaserScan, topic: /Hokuyo/scan, marking: true, clearing: true}

#point_cloud_sensor: {sensor_frame: frame_name, data_type: PointCloud, topic: topic_name, marking: true, clearing: true}
