global_costmap:
  global_frame: /map
  robot_base_frame: base_link
  update_frequency: 5.0
  static_map: false
  origin_x: -15.0
  origin_y: -15.0
  width: 20.0
  height: 20.0
  resolution: 0.5
  transform_tolerance: 1.0
