local_costmap:
  global_frame: odom
  robot_base_frame: base_link
  update_frequency: 5.0
  publish_frequency: 5.0
  static_map: false
  rolling_window: true
  width: 5.0
  height: 5.0
  origin_x: -2.5
  origin_y: -2.5
  resolution: 0.1
  transform_tolerance: 1.0
